<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.striim.util</groupId>
	<artifactId>StriimWatcher</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>StriimWatcher</name>
	<url>http://maven.apache.org</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<STRIIMBUILDPATH>
			/Users/danielferrara/Documents/Striim420
		</STRIIMBUILDPATH>
		<STRIIM_VERSION>
			4.2.0
		</STRIIM_VERSION>
		<STRIIMWatcher_VERSION>
			4.2.4
		</STRIIMWatcher_VERSION>
		<JACKSON_VERSION>
			2.14.0
		</JACKSON_VERSION>
	</properties>

	<dependencies>
		<dependency>
			<groupId>
				com.webaction
			</groupId>
			<artifactId>
				Platform
			</artifactId>
			<version>
				${STRIIM_VERSION}
			</version>
			<scope>
				system
			</scope>
			<systemPath>
				${STRIIMBUILDPATH}/lib/Platform-${STRIIM_VERSION}.jar
			</systemPath>
		</dependency>
		<dependency>
			<groupId>
				com.webaction
			</groupId>
			<artifactId>
				Common
			</artifactId>
			<version>
				${STRIIM_VERSION}
			</version>
			<scope>
				system
			</scope>
			<systemPath>
				${STRIIMBUILDPATH}/lib/Common-${STRIIM_VERSION}.jar
			</systemPath>
		</dependency>
		<dependency>
			<groupId>
				com.webaction
			</groupId>
			<artifactId>
				SourceCommons
			</artifactId>
			<version>
				${STRIIM_VERSION}
			</version>
			<scope>
				system
			</scope>
			<systemPath>
				${STRIIMBUILDPATH}/lib/SourceCommons-${STRIIM_VERSION}.jar
			</systemPath>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.17.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>2.17.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-jcl</artifactId>
			<version>2.17.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>
				joda-time
			</groupId>
			<artifactId>
				joda-time
			</artifactId>
			<version>
				2.9.7
			</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>
				com.esotericsoftware
			</groupId>
			<artifactId>
				kryo
			</artifactId>
			<version>
				2.20
			</version>
			<scope>
				system
			</scope>
			<systemPath>
				${STRIIMBUILDPATH}/lib/kryo-2.20.jar
			</systemPath>
		</dependency>
		<dependency>
			<groupId>
				com.fasterxml.jackson.core
			</groupId>
			<artifactId>
				jackson-core
			</artifactId>
			<version>
				${JACKSON_VERSION}
			</version>
			<scope>
				system
			</scope>
			<systemPath>
				${STRIIMBUILDPATH}/lib/jackson-core-${JACKSON_VERSION}.jar
			</systemPath>
		</dependency>
		<dependency>
			<groupId>
				com.fasterxml.jackson.core
			</groupId>
			<artifactId>
				jackson-databind
			</artifactId>
			<version>
				${JACKSON_VERSION}
			</version>
			<scope>
				system
			</scope>
			<systemPath>
				${STRIIMBUILDPATH}/lib/jackson-databind-${JACKSON_VERSION}.jar
			</systemPath>
		</dependency>
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20140107</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore</artifactId>
			<version>4.4.13</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-release-plugin</artifactId>
				<version>2.2.2</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>2.4.3</version>
				<configuration>
					<createDependencyReducedPom>false</createDependencyReducedPom>
					<finalName>StriimWatcher</finalName>
					<transformers>
						<transformer
								implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
							<manifestEntries>
								<Striim-Module-Name>StriimWatcher</Striim-Module-Name>
								<Striim-Service-Interface>com.webaction.proc.SourceProcess</Striim-Service-Interface>
								<Striim-Service-Implementation>com.striim.util.StriimWatcher</Striim-Service-Implementation>
							</manifestEntries>
						</transformer>
						<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
					</transformers>
					<artifactSet>
						<excludes>
							<exclude>org.slf4j:*</exclude>
							<exlcude>log4j:*</exlcude>
						</excludes>
					</artifactSet>
				</configuration>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.coderplus.maven.plugins</groupId>
				<artifactId>copy-rename-maven-plugin</artifactId>
				<version>1.0</version>
				<executions>
					<execution>
						<id>copy-file</id>
						<phase>package</phase>
						<goals>
							<goal>copy</goal>
						</goals>
						<configuration>
							<sourceFile>target/StriimWatcher.jar</sourceFile>
							<destinationFile>${STRIIMBUILDPATH}/UploadedFiles/StriimWatcher-${STRIIMWatcher_VERSION}.jar
							</destinationFile>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
